package com.godfirst.kareer.ui

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.fragment.navArgs
import com.godfirst.kareer.R
import com.godfirst.kareer.adapters.PathsRecyclerAdapter
import com.godfirst.kareer.databinding.FragmentPathsBinding
import com.godfirst.kareer.models.Paths
import com.godfirst.kareer.util.Constants

class PathsFragment : Fragment() {

    private var _binding: FragmentPathsBinding? = null
    private val binding get() = _binding!!
    val args: PathsFragmentArgs by navArgs()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        // Inflate the layout for this fragment
        _binding = FragmentPathsBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val path = args.career
        binding.titleText.text = path

        var pathList = emptyList<Paths>()

        when(path) {
            Constants.CONTENT_WRITING -> {
                pathList = listOf(
                    Paths("Research Writer", "Research writing is a type of writing that wields evidence from books, magazines, journals, experts, the internet, etc. Research writers take complex ideas and convert them into layman language so that everyone can comprehend them. Research Writers have apprehension of conducting extensive research and how to use and maintain databases. \n\nThese writers can be found in diverse fields most of them are scientific or technical. Research writers are adept at researching, organizing, analyzing, and explaining data. Research Writers thoroughly investigate the problems. They gather information with the help of diverse sources and write their thesis accordingly. Research writers write the research paper after extensive exploration.", R.drawable.content),
                    Paths("Medical Writer", "A medical writer is a person who applies the principles of clinical research in evolving clinical trial documents that effectively elucidate research inferences, product use, and other medical information. Medical writers share the latest health updates to be aware of current updates.Medical Writing Course helps you to evolve. Moreover, it leads to the production of digital documents that deal specifically with medicine or health care. \n\nMedical writers are indulged in communicating scientific data to a myriad of audiences. Medical writers ensure documents comply with the regulatory, publication, or other guidelines like content, format, structure, etc. Medical Writers work with doctors, scientists, and other subject experts.", R.drawable.content),
                    Paths("Technical Writer", "Technical writers are high in demand in all industries and are especially found in technical sectors. Before I tell you more about it, I want you to know that 'NO'- it does not require technical skills but if you learn it, it is definitely an advantage. These authors indulge in directing and explaining a subject. It majorly encompasses all documentation such as reports, white papers, handbooks, procedures, data sheets, proposals, manuals etc. \n\nIf you have a technical background, finding freelance content writing jobs becomes very easy. Technical writer jobs can be found under the searches for online content writing jobs or freelance content writing jobs. According to experts, there has been a positive shift in the graph for an increase in technical writer jobs. Several technical industries have started hiring writers under part-time content writing jobs just to make their content more supreme. Mega companies on the other side, have experts in technical writing to target their audience.", R.drawable.content),
                    Paths("Copywriter", "As a copywriter, you often write to sell. The whole idea focuses on marketing and advertising. It requires out of the box thinking. They aim to improve the sales of any company. It is written to create an impact using ATL (above the line) ads. \n\nYou can work it up as a freelance or online content writing job or even as a part-time content writing job . The main goal of your content should be to promote the USP (unique selling proposition) of any product. \n\nCopywriting as a content writing job involves a lot of creativity which you can only learn by devoting a few days to compelling write-ups. Your content should be able to generate attention, attract the interests of the mass, sow the seeds of desire and finally ask the reader to take the action. A lot falls at stake for the businesses that are bringing their product in public and it demands to be delivered at its best via content you create. You must have heard this quote \"an average writer writes, but a copywriter craft\".", R.drawable.content),
                    Paths("Blogger", "Blogging is like advanced level diary writing. Most people are aware of the idea about having a personal blog where one can publish contents of their interest or hobbies. Blogging as an online content writing job is little different from running an ordinary blog. You can work it as part-time or a full time blogger. It ranges from personal blogs to corporate blogs where you promote an idea or a product or information related to some news. \n\nOwning a personal blog with a niche works wonder in case of blogging as a content writing job . It sells the idea of your blog which then gets advertisements. An ad in your blog becomes one of the main sources of your daily income. When working for a corporate or company blog, you follow their idea and promote their brand through your content. It gives you a full time blogger job. Such blogs follow a pretty simple structure so as to not confuse their customers. Main motives are highlighting the objective in a transparent way. \n\nIn a personal blog, you can explore and test out various themes and designs to generate a unique profile. Also, not to overdo it should always be kept in mind while crafting your blog. You can start blogging as a part time content writing job in order to gain some confidence and experience.Some bloggers are nowadays turning into celebrated influencers who even collaborate with bigger and world-renowned organizations. Isn’t it amazing!!", R.drawable.content),
                    Paths("Social Media Manager", "Another promising content writing career opportunity is one of social media managers. Every business today is active on social media platforms. Social media marketing brings up their brand to a whole new audience. Business owners build their social media sites and hire people to manage their social networks to achieve active online presence. Social media managers constantly research, strategize, create, edit and publish high quality content to market the business. Freelance content writing jobs are flooded with the daily requirements of social media writers and managers. \n\nContent management and its channeling throughout the social media becomes the major task of the social media manager. It also includes managing advertising campaigns. Marketing tools like SEO come in proportional use when working for a social site. Social media writer could be one part of the content writing job ; however, most companies fit in this responsibility under the position of manager. \n\nWhen Searching for online content writing jobs , the job of social media manager can also go by title of digital marketing manager, community manager, or content marketing manager. \n" +
                            "Content writers are the priorities for the role of social media manager. It is also associated with creative writing when it comes to engaging the audience and generating customer demand. You do not have to have any management background for this job. ", R.drawable.content)
                )
            }
            Constants.DESIGN -> {
                pathList = listOf(
                    Paths("Graphic designer", "One of the most common design careers out there is a graphic designer. These professionals create designs for marketing collateral, product illustrations, brand identities and websites using computer software like the Adobe® Creative Suite. \n\nThey merge technical skill with artistic ability to create a design that resonates with its desired audience. Graphic designers may work independently as freelancers or contractors, in an in-house setting for a company or in an agency setting.", R.drawable.design),
                    Paths("User experience (UX) designer", "UX designers make websites, mobile applications, software and video games easier to navigate and more intuitive for users to interact with. They study and evaluate how people feel about a particular system and design their products to cater to the needs of the user. They also analyze the specific components of the systems, such as usefulness, value, credibility and accessibility. \n\nFor example, a UX designer might work with a retailer to update their product webpages and mitigate issues, like frustrating forms, hard-to-find buttons and visual clutter, that can prevent users from making a purchase.", R.drawable.design),
                    Paths("User interface (UI) designer", "A close relative of user experience design, this specialized design role is focused on creating (or improving existing) interfaces. Not sure what that means? Think of the menu systems of your favorite apps or the touchscreen displays you see in vehicles—those are prominent examples of an interface, and a lot of careful consideration goes into ensuring they’re intuitive, aesthetically pleasing and easy to navigate. \n\nThis role requires user empathy and the ability to balance the needs of the user and the needs of the application’s creator. Typically, UI design requires a mix of design, psychology and development know-how to be successful.", R.drawable.design),
                    Paths("Photographer", "Photographers utilize their creativity and composition skills alongside their technical expertise to capture photographs that tell a story or document an event. The majority of today’s photographers work with digital cameras and editing software to capture subjects in commercial-quality images. Some travel to a location to shoot an event or scenery while others have their own studios for portraits, commercial shoots or artistic work.", R.drawable.design),
                    Paths("Interior designer", "Professionals in this occupation work with interior spaces to improve the safety, functionality and aesthetic appeal of the area. They select color schemes, furniture, flooring, lighting and all other elements of a room or building. Interior designers also sketch their ideas or use design software to communicate their plans with the architects, structural engineers and builders who bring their designs to life.", R.drawable.design),
                    Paths("Multimedia artist & animator", "These professionals create animations and special effects for movies, television, video games and other forms of media—both two-dimensional and three-dimensional. They work with teams of animators and artists to bring ideas to life using computer software or by writing their own computer codes. Some work in studios or offices, but many are self-employed and work from home.", R.drawable.design),
                    Paths("Art director", "Typically a role reserved for experienced design professionals, art directors work in a variety of settings, such as magazines, newspapers, internet-based publications, and advertising or public relations agencies. They communicate with clients while overseeing project budgets and timelines. They manage a team of design professionals, reviewing and approving all creative materials before presenting to clients.", R.drawable.design),
                    Paths("Fashion designer", "Professionals in this field design new clothing and accessories. Designs are sketched on paper or digital devices, and then colors, materials and textures of the final product are determined. Fashion designers study fashion trends by reviewing magazines and attending fashion shows. They then provide sample garments to sales representatives and agents in hopes of selling their own collections.", R.drawable.design),
                    Paths("Film & video editor", "Film and video editors use technical software to construct promotional or artistic productions from footage shot by camera operators. This creative career involves working with directors and producers to determine which material is most captivating for their audience and to help piece together scenes. The editing process involves trimming footage down into segments, marking frames for audio, and organizing raw footage into a seamless and polished final product.", R.drawable.design)
                )
            }
            Constants.HUMAN_RESOURCE -> {
                pathList = listOf(
                    Paths("Chief Human Resources Officer",
                        "If you are good at HR and like being a key decision-maker in an organization, then a chief human resources officer is the job for you. The chief human resources officer is the top position you can obtain if you are on the human resources executive track. A chief HR officer requires you to develop HR strategies, policies, and goals for your company. \n\nSome of the duties of a chief HR officer include: Leading and supervising human resources managers in the HR division, Communicating HR efforts to support and implement the strategic vision of the company, Functioning as a business advisor to the CEO and other C-level executives and managers, Developing strategies for recruiting and retaining employees, managers, and executives, Developing compensation and benefit plans, and Providing career development, training, leadership development, and retention guidance. \n\nAs a chief HR officer, you are responsible for every aspect of the human resources department. You will need to demonstrate excellent organizational, analytical, supervisory, interpersonal, and communication skills. The chief HR officer position requires you to have a minimum of 15 years of human resources experience. Your HR experience should include a minimum of five years in a management position. The average salary of a chief HR officer is \$214,432. Top income earners in this position can make up to \$340,090. This salary does not include bonuses, which can be up to an additional \$75,000.", R.drawable.human_resources),
                    Paths("Human Resources Manager or Director",
                    "Some companies have a human resources manager, while others have an HR director. Regardless of the title, human resources managers and directors have similar roles. HR managers and directors get the benefit of directly interacting and helping employees. They also work with the chief HR officer to plan, coordinate, execute, and manage HR activities. They are involved in guiding employees through the hiring process, explaining benefit programs, training employees, handling labor disputes, and other administrative tasks that are important to workers within a company. Human resources managers and directors are also called upon to serve as consultants on various issues. These issues could include equal employment opportunities, labor laws, and sexual harassment. They have a direct influence and positive impact on the people in a company. Helping others leads to many social benefits and the satisfaction of having a real impact on your fellow human beings. The median annual income for an HR manager or director position is \$116,720, and top income earners can make up to \$205,720.", R.drawable.human_resources),
                    Paths("Training and Development Manager",
                    "Training and development managers help employees improve their skill sets and human resources careers. They accomplish this by conducting continuing education classes, workshops, conferences, and other kinds of gatherings. Training and development managers may design the most effective coursework for employees that their organization wants to emphasize. \n\nSome of their other duties include: Assessing employees’ training needs, Reviewing training materials from outside vendors, Teaching and supervise other instructors, and Updating training programs to meet current organizational standards. \n\nYou will find this career very fulfilling if you like standing up in front of people and helping them learn new skills that will improve their career prospects. Training and development managers make an average of \$113,350 and can make as high as around \$200,000 a year.", R.drawable.human_resources),
                    Paths("Human Resources Consultant",
                    "These days, companies are more complicated than ever before. Human resources departments are no exception. Sometimes a human resources department needs an outside perspective to solve a problem. This is when they call a human resources consultant for advice and guidance. Human resources consultants charge companies an hourly rate to provide them with much-needed services. Human resources consultants may specialize in one or more fields like workplace harassment, labor laws, employee acquisition, retainment, compensation and benefits, employee incentives and rewards programs, company culture after mergers and acquisitions, or employee motivation. A human resources department may even outsource some of its functions to a human resources consultant. Human resources consultants assess a company’s current situation and offer systemic recommendations. This will help get the HR department and the company to its desired goal. Meanwhile, the HR consultant gets to choose who they work with, when they work, and what to charge. Many HR consultants only get paid when they accept and complete a job. Their average annual compensation can range from \$50,000 to \$110,000.", R.drawable.human_resources),
                    Paths("Executive Recruiter",
                    "If you are good at building relationships, a position as an executive recruiter could be a lucrative way to earn a living. Executive recruiters are tasked with finding candidates to fill job openings for C-level executives, senior executives, corporate officers, and directors. Executive recruiters generally get paid on retainers or paid in full after they have filled a position. Executive recruiters can charge large fees because companies are always in need of good senior talent. Executive recruiters need to build solid relationships with companies so that when an opening occurs, these companies call them first. At this point, the recruiter will launch their search and contact executives from other companies who are looking for better opportunities. Executive recruiting is a competitive field. The companies who hire you expect you to bring them the best candidates. If you are successful, you can earn up to \$135,000 a year or more.", R.drawable.human_resources),
                    Paths("Labor Relations Manager",
                    "Being a labor relations manager is the job for you if you like negotiating contracts and getting the best deal possible for the workers. These managers act as a mediator between the employees and employer on behalf of a labor union that represents the employees. When there is a dispute between management and a labor union, the manager helps both sides come to an agreement on issues such as wages, pensions, health benefits, work environment, and management practices. \n\nSome of the other duties a labor relations manager will encounter include: Drafting proposals on rules and regulations for collective bargaining agreements, Conducting meetings and being a line of communication between management and labor, Advising and training management on labor relations, labor grievances, and disciplinary procedures, and Ensuring human resource policies comply with union agreements. \n\nThis is a job where you will need to have good decision-making, listening, interpersonal, and writing skills. You will also need to be detail-oriented when dealing with labor laws. \$69,020 is the median annual salary of a labor relations manager. A top manager can earn up to \$124,380 a year.", R.drawable.human_resources)
                )
            }
            Constants.PROGRAMMING -> {
                pathList = listOf(
                    Paths("Software application developer", "Software developers are responsible for creating and enhancing applications for cell phones, tablets and other mobile devices. This is an ideal programming career for someone who has a “big picture” mentality and likes to collaborate with others to bring ideas to life. Knowing coding basics and having an aptitude for math are also important.", R.drawable.programming),
                    Paths("Web developer",
                    "How a website looks and functions is the direct result of a web developer’s work. All programming careers take patience, but this one provides more instant gratification than most. Web developers listen well to their clients’ needs and problem-solve to give them the best website possible for their business. At the end of a project, you have a working, accessible website to show off your hard work. Web developers do well when they can show a portfolio of their work and have a deep understanding of coding.", R.drawable.programming),
                    Paths("Computer systems engineer",
                    "Computer systems engineers are responsible for identifying solutions to complex applications problems, systems administration issues or network concerns. They work closely with clients or internal stakeholders to understand system needs and collaborate with developers to determine appropriate solutions. This is another programming career that is ideal for business-savvy professionals.", R.drawable.programming),
                    Paths("Database administrator",
                    "Database administrators are tasked with securing, organizing and troubleshooting storage for large amounts of information for companies online. If you love analyzing and recovering information, as well as fast problem-solving, this could be the coding career for you.", R.drawable.programming),
                    Paths("Computer systems analyst",
                    "Computer systems analysts are the strategists who are responsible for merging a company’s business and information technology (IT) initiatives. They evaluate computer network systems and propose upgrades to meet business needs. You’ll need to have a solid understanding of computer coding as well as the business side to succeed in this programming career.", R.drawable.programming),
                    Paths("Software quality assurance (QA) engineer",
                    "Software QA engineers are at the beginning of software, documenting defects, designing tests and scenarios, and creating manuals for new software. They also review software designs for functionality and potential problems.", R.drawable.programming),
                    Paths("Network system administrator",
                    "Network system administrators maintain computing environments in their networks and prevent disasters by backing up data. Providing network security and avoiding viruses are the major tasks, along with making sure codes are free of errors and protecting both the network and hardware of the computers.", R.drawable.programming)
                )
            }
            Constants.DIGITAL_MARKETING -> {
                pathList = listOf(
                    Paths("Content Managers & Strategists", "Content management is a central role for any agency or digital marketing team as it touches on almost all levels of marketing – and it encompasses much more than just writing and social media activity. Content Managers need to not only understand how to create SEO-optimized content but how to organize, store, and manage it effectively. They need to understand how content feeds into different subsets of the marketing plan and grasp how to develop and share the content assets on the right channels. \n\nContent managers may be in charge of social media strategy, managing a team of writers, forming an effective editorial calendar, creating engaging videos, reporting and strategizing using analytics, and a whole range of related activities. To do this, they need to coordinate teams and work with a diverse range of clients. \n\nSo, a good Content Manager, not only needs to be a great writer but also create stellar content that works across multiple channels. They also need to be good at relationship building, creative, organized and self-motivated. \n\nEarning potential: \$61,000 (€52,000) and upwards annually according to Payscale.", R.drawable.digital_marketing),
                    Paths("SEO/SEM Specialists", "SEO and SEM are crucial for solid digital marketing campaigns and anyone who can demonstrate technical knowledge and digital marketing expertise, especially in terms of management, will be the highest earners in this field. SEO and SEM can be difficult to specialize in, in part because search engine algorithms are always fluctuating. Businesses must stay up-to-date and understand how they work together to have a consistently high ROI and the bigger the business is, the more complex this can be. In addition, e-commerce sites and those that depend on website traffic for profits will be particularly dependent on a strong and harmonious SEO/SEM strategy. \n\nMost businesses will want to rank high on search engine results, so they need people with expertise in these areas. According to SEO Basics, the demand for SEM specialists is growing at almost 100% per year while the demand for SEO specialists keeps growing to the extent that there’s a skills shortage in the jobs market. \n\nEarning potential: The average salary for these types of jobs is \$49,174 (€42,507) annually, but more experienced SEO/SEM specialists and analysts can expect to earn at least \$66,000 (€57,000) annually.", R.drawable.digital_marketing),
                    Paths("Email Marketing Specialist", "Email marketing is an example of a specialized area of content development and marketing. People in charge of email marketing are competent marketers with experience in copywriting and editing. Email continues to be one of the most effective content formats out there. To do this well, you need to write persuasively and understand how to create an effective email marketing strategy. You’ll also be in charge of campaigns, launches, and PR activities based on an extensive database of customer data and lists. The quality of your email contacts is key to driving email marketing success so it’s crucial to know ways to grow your database without annoying prospects. \n\nEmail marketing is primarily a lead-generating activity and so specialists would work in cooperation with digital marketing and/or content managers on targeted campaigns to convert leads into sales. \n\nEarning potential: Email Marketing Specialists can expect to earn an average base salary of around \$57 000 USD (€49,000) according to LinkedIn, which can jump to \$65,000 (€56,000) depending on experience.", R.drawable.digital_marketing),
                    Paths("Digital Marketing Managers & Directors", "CMO's and VP's can expect to earn over \$100,000 a year, as can Creative Directors. This takes years of experience in the field but can be fast-tracked if you have plenty of managerial experience under your belt. An effective Digital Marketing Manager or Creative Director must have a solid grasp of everything to do with marketing and business. They must have proven experience in strategic planning and execution including creating a digital marketing strategy, as well as financial forecasting. Anyone in this position should also be able to delegate while taking risks, hold firm on decisions, and plan for the future through leadership. \n\n Earning potential: Digital Marketing Managers and Directors can expect to earn a similar salary as other marketing managers, which averages at \$109,000 (€94,000) according to salary.com and soars up to \$148,000 (€127,000) for the most experienced.", R.drawable.digital_marketing)
                )
            }
            Constants.CUSTOMER_SERVICE -> {
                pathList = listOf(
                    Paths("Customer Service Representative",
                        "Customer service representatives go by many names––agents, customer experience managers, or even white glove support specialist. But at their core, the role of these front-line individuals is to resolve any customer issues. Customer service representatives are the face of the company as they help answer customer questions, resolve complaints, process and modify orders, and provide instructional information about products and services. \n\nQualifications: \nHigh school diploma or higher, Strong communication skills (especially patience, empathy, and problem-solving), Basic computer skills, Experience in customer service preferred, but not required. \n\nResponsibilities: \nRepresent the brand in every interaction, Deliver best-in-class service with professionalism and empathy, Provide support for customer inquiries on a variety of topics and channels, Respond efficiently and thoroughly to customer requests, Remain calm and professional in stressful situations. \n\nAverage Salary: \n\$39,460(Source: Payscale).", R.drawable.customer),
                    Paths("Quality Assurance Manager",
                    "Customer service quality assurance managers are the key to ensuring that customer service representatives adhere to a set of quality standards and deliver a great customer experience. Quality standards can include everything from tone to problem-solving ability, and are often specific to an individual company. Depending on the structure of the organization, quality assurance managers may be responsible for establishing and iterating on quality standards, evaluating agent performance, leading calibration sessions, and working with team leads to ensure they are coaching their agents effectively. \n\nQualifications \nBachelor’s degree or higher, Ability to analyze existing processes and propose solutions, Detail oriented with excellent communication skills, Experience in customer service management, Deep understanding of industry standards and Quality assurance certification preferred, but not required. \n\nResponsibilities \nEstablish and iterate on quality assurance standards, Facilitate quality training and development, Analyze data to identify trends in agent performance, Work with team leads to identify coaching opportunities, and Lead calibration sessions to ensure QA is consistent across the organization. \n\nAverage Salary\n\$81,287 (Source: Payscale).", R.drawable.customer),
                    Paths("Product Support Specialist",
                    "Product support specialists are subject matter experts on the product or services offered by a company. Where a customer service representative can field basic questions around orders or complaints, a product support specialist knows the ins and outs of how the product works, and can answer more complicated questions, troubleshoot problems, and serve as an educational resource on product functionality. \n\nQualifications \nBachelor’s degree or higher, Excellent communication skills, Technical certification (depending on the industry), and Prior experience in product-specific customer support. \n\nResponsibilities \nTroubleshoot customer product issues, Explain new functionality to customers, Update customers on long-term fixes, Share customer feedback with product team, Support contact center agents in resolving product-related service requests, Record common customer problems for product documentation, internal knowledge bases, and agent response templates. \n\nAverage Salary\n\$54,106 (Source: Payscale).", R.drawable.customer),
                    Paths("Customer Service Training Manager",
                    "Customer service training managers create learning and development programs for new and existing customer service representatives, implement new training processes, and iterate as needed. This includes everything from new hire training to management training and beyond. This role requires ongoing maintenance of training materials and innovation around the best training methods. Training managers are responsible for understanding all customer service processes from basic problem solving to technical product troubleshooting. \n\nQualifications \nBachelor’s degree or higher, 5+ years of relevant experience, Excellent communication skills, Experience implementing successful training program, Deep understanding of training tactics (ie. manager coaching, on-the-job vs in-classroom training, e-learning, etc.). \n\nResponsibilities \nEvaluate existing training programs, Create new training materials and processes to optimize the customer service function, Stay abreast of new learning and development tools and implement where relevant, Maintain learning management systems and internal agent knowledgebase, Work closely with product, sales, and marketing teams to ensure that agent training is aligned across the organization, and Measure and report on the success of training programs. \n\nAverage Salary\n\$58,631 (Source: Payscale).", R.drawable.customer),
                    Paths("Customer Retention Specialists",
                    "Rather than reactive troubleshooting, customer retention specialists provide proactive support to help customers get the most out of their product. This function is designed to help increase customer retention, loyalty, and drive upsells or repeat business over time. Customer retention specialists also handle contract renewal or cancellation requests. In this role, rather than solving a specific issue, specialists work to maximize the customer relationship. \n\nQualifications:\nHigh school diploma or higher, Strong communication skills, Basic computer skills, and Experience in customer service or sales preferred but not required. \n\nResponsibilities: \nProactively look for opportunities to engage or delight customers, Provide updates around new product features and tips to make the most out of the product, Monitor usage and engagement activity to identify pre-churn, Negotiate contracts and look for opportunities to upsell. \n\nSalary:\n\$47,500 (Source: Payscale)", R.drawable.customer)
                )
            }
        }

        binding.backImage.setOnClickListener {
            requireActivity().onBackPressed()
        }

        binding.pathsRecycler.apply {
            setHasFixedSize(true)
            adapter = PathsRecyclerAdapter(pathList)
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}